#pragma once

// clang-format off
// generated by ./scripts/sqlpp23-ddl2cpp --path-to-ddl tests/postgresql/recipes/enums_table.sql --path-to-header tests/postgresql/recipes/enums_table.h --namespace test --assume-auto-id --generate-table-creation-helper

#include <optional>

#include <sqlpp23/core/basic/table.h>
#include <sqlpp23/core/basic/table_columns.h>
#include <sqlpp23/core/name/create_name_tag.h>
#include <sqlpp23/core/type_traits.h>

namespace test {
  template<typename Db>
  void createTabEnums(Db& db) {
    db(R"+++(DROP TABLE IF EXISTS tab_enums)+++");
    db(R"+++(CREATE TABLE tab_enums (
  animal bigint,
  -- cpp_type:shape_type
  shape shape_type
))+++");
  }

  struct TabEnums_ {
    struct Animal {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(animal, animal);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    struct Shape {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(shape, shape);
      using data_type = std::optional<shape_type>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(tab_enums, tabEnums);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Animal,
               Shape>;
    using _required_insert_columns = sqlpp::detail::type_set<>;
  };
  using TabEnums = ::sqlpp::table_t<TabEnums_>;

} // namespace test
